<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- CSS -->
	<link rel='stylesheet' href='style.css'>
<!-- 	JS -->
	<link rel='stylesheet' href='http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css' />
	<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
	<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
	<script src="index.js"></script>
	<title>Exercice A Creads</title>
</head>
<body>

	<div class="globale">
		<div id="container">
			<div id="img">
				<img class="src_img" src="coeur.jpg" />
				<div id="box"></div>
			</div>
		</div>
		<div id="btn">
			<button id="crop_button"> Crop </button>
			<button id="reset_img"> Reset Image </button>
			<a href="/new.jpg" target="_blank"><button id="link_img">Show new image</button></a>
		</div>
	</div>
</body>
</html>